### ISSUE TITLE
Per-unit fallback compilation is broken for selector languages (regression from #437)

### ISSUE THREAD

**Issue by TomNaessens** [dodona-edu/universal-judge#657]
**TLDR:** when precompilation fails and we fall back to per-unit compilation, the fallback is broken for every selector-based compiled language (C, C#, Java, Kotlin, Haskell). C++ is the only one that survives. It's a silent regression from #437 (Rework execution), and it means partial solutions on those languages get "compilation error" on every context instead of partial feedback.

## What's wrong

When precompilation fails we re-plan to `TAB` and recompile each unit on its own in `ExecutionN/`. `set_up_unit` (via `filter_dependencies`) keeps the submission, the support files and the selector, but drops the *sibling* execution files. The catch: the selector is generated once over *all* units, so in `Execution0/` it still references `Execution1`, which is no longer there. For the symbol/include-based selectors that's a hard compile error:

```
Execution0/Selector.cs(16,21): error CS0103: The name 'Execution1' does not exist in the current context
selector.c:7: fatal error: execution_1.c: No such file or directory
```

C++ dodges it because its selector wraps every reference in `#if __has_include(...)`, so an absent sibling is simply skipped. The other five don't have that guard, and for C#/Java/Kotlin you can't have one (there's no "compile this branch only if the class exists").

There's a second, related problem hiding behind it: the fallback re-plans to `TAB` but never *regenerates* the execution files. For stdin exercises that's masked (OPTIMAL already splits per testcase, so the files line up), but for function/expression exercises OPTIMAL merges everything into one `Execution0` file, and the per-tab fallback then references files that were never generated. So function exercises fall over even harder, in every language including C++.

## Why it matters

The case where this actually bites students is a partial solution on a compiled language. If you've implemented `add` but not yet `subtract`, the combined precompile fails (the harness for `subtract` won't compile), we fall back, and right now *every* context comes back as "compilation error" (often with empty messages), instead of "your `add` passes, `subtract` doesn't compile yet". That's a pretty common "I've done half the functions" situation in intro courses.

(For C# specifically the recent #596 work already skips the fallback for *submission*-level compile errors, so the remaining value there is really the partial-function case. The other compiled languages aren't covered by that.)

## Where it came from

It's a regression from #437 (Rework execution, merged 2023-09-20). Before that we had an explicit `ExecutionMode` (`PRECOMPILATION` / `INDIVIDUAL`), and the per-context (`INDIVIDUAL`) path set each context up on its own, with the selector generated *only* for PRECOMPILATION mode, so the per-context path never had an all-units selector to dangle. #437 removed the mode dispatch and made the fallback reuse the precompile artifacts instead:

```diff
-    mode = bundle.config.options.mode
-    if mode == ExecutionMode.PRECOMPILATION:
-            if status != Status.CORRECT and bundle.config.options.allow_fallback:
-                mode = ExecutionMode.INDIVIDUAL
+    if status != Status.CORRECT and bundle.config.options.allow_fallback:
-    if mode == ExecutionMode.PRECOMPILATION and ...needs_selector():
-        _logger.debug("Generating selector for PRECOMPILATION mode.")
```

The `ExecutionMode` enum and the `mode` option are still in the code but nothing reads them anymore. To be clear: #437 was solving #329 (merge across tabs) and #433 (testcase ordering), both of which are fine and which a fix here shouldn't touch. The mode removal and the broken fallback were silent side effects, never tracked.

## Reproducing it

You can't trigger it cleanly from a normal submission (a real submission compile error fails every unit anyway, masking the selector), so the probe forces *only* the trigger and keeps the compilation real: it mocks `precompile` to report a failure on a *correct* submission, so the per-unit fallback actually runs.

<details><summary>probe + how to run it</summary>

```python
# tests/test_fallback_selector.py
import pytest
from pytest_mock import MockerFixture
from tested.dodona import Status
from tested.judge.planning import CompilationResult
from tests.manual_utils import assert_valid_output, configuration, execute_config

@pytest.mark.parametrize("language", ["cpp", "csharp", "c", "java", "kotlin", "haskell"])
def test_fallback_selector(language, tmp_path, pytestconfig, mocker: MockerFixture):
    mocker.patch("tested.judge.core.precompile",
                 return_value=CompilationResult(status=Status.COMPILATION_ERROR, messages=["forced"]))
    conf = configuration(pytestconfig, "echo", language, tmp_path, "two.tson", "correct",
                         {"options": {"allow_fallback": True}})
    s = assert_valid_output(execute_config(conf), pytestconfig).find_status_enum()
    print(f"\n>>> {language:8} {'RESCUED' if 'compilation error' not in s else 'BROKEN '} {s}")
```

```bash
docker run --rm --platform linux/amd64 -v "$PWD":/judge -w /judge \
  ghcr.io/dodona-edu/dodona-tested \
  bash -c 'python3 -m pip install -q pytest pytest-mock; \
           python3 -m pytest tests/test_fallback_selector.py -s -q -p no:cacheprovider 2>&1 | grep ">>>"'
```
</details>

On `master` today:

```
cpp      RESCUED  ['correct', 'correct']
csharp   BROKEN   ['compilation error', 'compilation error']
c        BROKEN   ['compilation error', 'compilation error']
java     BROKEN   ['compilation error', 'compilation error']
kotlin   BROKEN   ['compilation error', 'compilation error']
haskell  BROKEN   ['compilation error', 'compilation error']
```

## A prototype fix

The selector half is tiny. In `set_up_unit`, after the deps are linked in, give each unit a selector that names only itself:

```python
# give each unit a selector naming only itself, so the filtered-out
# sibling units leave no dangling references.
if bundle.language.needs_selector():
    selector_path = execution_dir / selector_file(bundle.language)
    selector_path.unlink(missing_ok=True)            # drop the all-units hardlink
    generate_selector(bundle, execution_dir, [unit.name])
```

`generate_selector` already takes a name list, so `[unit.name]` yields a one-branch selector and the symbol-based languages are handled the same as the include-based ones, no `__has_include` trickery. With this, all five flip to RESCUED, the existing C# compile tests stay green, and the normal-path output is unchanged:

```
cpp      RESCUED
csharp   RESCUED   ← was BROKEN
c        RESCUED   ← was BROKEN
java     RESCUED   ← was BROKEN
kotlin   RESCUED   ← was BROKEN
haskell  RESCUED   ← was BROKEN
```

This is only the selector (the first bug). The second bug, the file-regeneration, is the half that actually matters for partial solutions: the fallback re-plans to `TAB` but reuses the `OPTIMAL` execution files, so for function/expression exercises (where `OPTIMAL` merges everything into one `Execution0`) the per-tab fallback references files that were never generated. I've now prototyped that one too, regenerating the execution files for the re-planned units right after the re-plan:

```python
planned_units = plan_test_suite(bundle, strategy=PlanStrategy.TAB)
plan.units = planned_units
# regenerate the execution files for the TAB units, so each tab gets its
# own file instead of the merged OPTIMAL one
deps = bundle.language.initial_dependencies()
deps.append(submission_file(bundle.language))
names = []
for u in planned_units:
    generated, evaluators = generate_execution(
        bundle=bundle, destination=plan.common_directory, execution_unit=u
    )
    for ev in evaluators:
        shutil.copy2(Path(bundle.config.resources) / ev, plan.common_directory)
    deps.extend(evaluators); deps.append(generated); names.append(u.name)
if bundle.language.needs_selector():
    deps.append(generate_selector(bundle, plan.common_directory, names))
plan.files = deps
```

With both halves in, a real partial solution (no mock) on an add/subtract exercise finally does the right thing: the tab whose function is implemented compiles and passes, and only the missing one fails to compile.

```
C# COMPLETE (sanity):   Optellen -> correct          Aftrekken -> correct
C# PARTIAL (add only):  Optellen -> correct          Aftrekken -> compilation error
C++ PARTIAL (add only): Optellen -> correct          Aftrekken -> compilation error
```

So together the two are basically "restore the per-context setup that #437 removed", which is also what wiring the dead `mode = "context"` option back up would amount to. The existing C# compile tests stay green with both patches in. Both are still rough though: the file-regen one is inlined rather than extracted, isn't gated to the fallback, and doesn't yet handle `OPTIMAL` having produced more units than `TAB` (which would leave stale files).

A small refinement for a real fix: `set_up_unit` runs in the normal precompile path too, where regenerating the selector is a harmless no-op (the binary's already built), but it'd be cleaner to only do it when we're actually about to compile per-unit.

## Open questions

- Do we want to fix this, or is the fallback rare enough that it's not worth it? The honest value is "partial solutions on compiled languages get partial feedback instead of all-red".
- If we fix it: minimal selector-regen + file-regen, or properly resurrect the `INDIVIDUAL` / `"context"` mode? And do we then remove or revive the orphaned `ExecutionMode` / `mode` option?

Open to alternatives, this is just what I found while poking at #596. What do you think? 🤔
